FROM node:18-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

COPY . .
RUN npm run build message-microservice

EXPOSE 3004

CMD ["node", "dist/apps/message-microservice/main"]