FROM node:18-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

COPY . .
RUN npm run build user-microservice

EXPOSE 3002

CMD ["node", "dist/apps/user-microservice/main"]